name: 'ESP-MDF Project Build'
author: 'qdlmcfresh'
description: 'GitHub action to install ESP-MDF tools for building esp-mdf projects'

branding:
  icon: 'box'
  color: 'orange'

inputs:
  fetch-depth: 
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags'
    required: false
    default: '1'
  token:
    description: 'Personal access token (PAT) used to fetch the repository'
    required: false
    default: ${{ github.token }}
  submodules:
    description: 'Whether to checkout submodules: true to checkout submodules or recursive'
    required: false
    default: false
  esp_mdf_version:
    description: 'ESP-MDF version'
    required: false
    default: 'v1.0'
  esp_mdf_commit:
    description: 'ESP-MDF commit'
    required: false
    default: ''
  esp_mdf_target:
    description: 'Sets the target (chip) for which the project is built'
    required: false
    default: 'esp32'

runs:
  using: "composite"
  steps:
    - name: Checkout the code
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
        submodules: ${{ inputs.submodules }}
    
    - name: Cache esp-mdf and its tools
      id: esp-mdf-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/esp/esp-mdf
          ~/.espressif
        key: ${{ runner.os }}-esp-${{ inputs.esp_mdf_version }}

    - run: |
        if echo ${{ steps.esp-mdf-cache.outputs.cache-hit }} | grep -c "true"
        then 
          echo "Cache hit - skipping dependency installation"
        else
          sh ${{ github.action_path }}/install.sh ${{ inputs.esp_mdf_version }} ${{ inputs.esp_mdf_commit }}
        fi
      shell: bash

    - run: |
        source ~/esp/esp-mdf/esp-idf/export.sh
        export MDF_PATH=~/esp/esp-mdf
        idf.py set-target ${{ inputs.esp_mdf_target }}
        idf.py build
      shell: bash
